### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by anmolbabu**
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Please don't merge until I mark it verified(although the fixes here are verified) as there are few more fixes that need to move in

**Comment by r0h4n** [comment]
Are these verified now?

**Comment by anmolbabu** [comment]
@r0h4n Yes these are verified but some more fixes(enhancements + duplicate alert filtering) are being worked upon. The issues that are being worked upon are not showstoppers but without fixes the functionality can look ugly. Please merge this PR and I'll raise another PR for those(as they are not blockers)

**Comment by anmolbabu** [comment]
Verified now...

**Pull request merged**
